server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: ecommerce-api

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=EcommerceDB;encrypt=true;trustServerCertificate=true;
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: 123

  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: llama3

app:
  jwt:
    secret: YTJiM2M0ZDVlNmY3ZzhoOWkwajFrMmwzbTRuNW82cDdxOHI5czB0MXUydg==
    expiration-ms: 86400000  # 24 hours
  cors:
    allowed-origins: http://localhost:4200,http://localhost:4201
